import { Language, Project, Technology, Tool } from '@shared/interfaces/develop';
import { Languages, Tools, Technologies } from '@shared/dtos/develop';

export const LANGUAGES: Array<Language> = [
  Languages.javascript,
  Languages.typescript,
  Languages.dart,
  Languages.java,
];

export const TOOLS: Array<Tool> = [
  Tools.npm,
  Tools.git,
  Tools.webpack,
  Tools.webstorm,
  Tools.firebase,
  Tools.sonar,
  Tools.gla,
  Tools.zeplin,
  Tools.figma,
  Tools.jenkins,
  Tools.aws,
  Tools.jira,
  Tools.azure,
];

export const TECHNOLOGIES: Array<Technology> = [
  Technologies.node,
  Technologies.express,
  Technologies.mysql,
  Technologies.postgresql,
  Technologies.mongo,
  Technologies.webStorages,
  Technologies.rest,
  Technologies.graphql,
  Technologies.html,
  Technologies.css,
  Technologies.react,
  Technologies.reactNative,
  Technologies.flutter,
  Technologies.angular,
  Technologies.materialUI,
  Technologies.semanticUI,
  Technologies.kendoUI,
  Technologies.bootstrap,
  Technologies.oop,
  Technologies.fp,
  Technologies.tdd,
  Technologies.bdd,
  Technologies.redux,
  Technologies.mobx,
  Technologies.jest,
  Technologies.lodash,
  Technologies.svg,
  Technologies.d3js,
  Technologies.canvas,
  Technologies.webSocket,
  Technologies.webWorker,
  Technologies.serviceWorker,
  Technologies.jsdoc,
  Technologies.scrum,
  Technologies.kanban,
  Technologies.lean,
  Technologies.exp,
];

export const PROJECTS: Array<Project> = [
  {
    name: 'Wineshipping',
    description: `The most comprehensive alcohol logistics network in the U.S. Fast and reliable service, warehouses near your customers, personalized support, and the innovative technology that powers our network…`,
    technologies: [
      Languages.typescript,
      Technologies.react,
      Technologies.redux,
      Technologies.webSocket,
      Technologies.materialUI,
      Technologies.svg,
      Technologies.lodash,
      Technologies.jest,
      Tools.webpack,
      Tools.figma,
      Tools.azure,
    ],
    responsibilities: [
      'Develop, manage application pages, UI components, animations, optimization',
      'Conduct regular code reviews to improve code quality',
      'Collaborate with BA on defining User Stories',
      'Mentoring of junior developer',
      'Lighthouse optimization',
      'Bug fixing',
    ],
    countryCode: 'us',
    period: '10 months',
  },
  {
    name: 'goScore',
    description: `goScore is an app built with both NFL fans and bettors in mind, though the app's main market is those who would place a bet on a game but don't know how to or aren't aware of exactly what's on offer to them. With attractive visuals and unique data manipulations, goScore's selection of tools offers an insight into the game that can't be found elsewhere.`,
    technologies: [
      Languages.typescript,
      Languages.objectiveC,
      Technologies.reactNative,
      Technologies.redux,
      Technologies.webSocket,
      Technologies.svg,
      Technologies.cryptoJS,
      Technologies.lodash,
      Technologies.googleMaps,
      Tools.zeplin,
      Tools.jira,
    ],
    responsibilities: [
      'Develop, manage application pages, UI components, animations, optimization, analytics',
      'Conduct regular code reviews to improve code quality',
      'Collaborate with Product Owners on defining User Stories for team',
      'Provide regular build to App Store, Google Play',
      'Implementation of non standard animation transitions, interpolations',
      'Huge optimization of component rendering model, performance analysis',
      'Bug fixing',
    ],
    countryCode: 'gb',
    period: '2 years',
  },
  {
    name: 'Seasoned',
    description: 'Leading provider of technology solutions for the restaurant and hospitality industries. The company will aim to remove friction, reduce cost and improve matching outcomes of current hiring solutions within the foodservice industry. It is the first foodservice-centric community designed to connect workers with jobs, talent and career development opportunities.',
    technologies: [
      Languages.javascript,
      Technologies.react,
      Technologies.redux,
      Technologies.materialUI,
      Tools.docker,
      Tools.webpack,
      Tools.jira,
    ],
    responsibilities: [
      'Conduct regular code reviews to improve code quality',
      'Collaborate with Product Owners on defining User Stories for team',
      'Completes applications development by coordinating requirements, schedules, and activities',
      'Lighthouse optimization',
      'Bug-fixing',
    ],
    countryCode: 'us',
    period: '6 months',
  },
  {
    name: 'Colligo',
    description: 'A healthcare company which collaborates with a wide range of occupational categories in healthcare and specialize in nursing and medical care.',
    technologies: [
      Languages.javascript,
      Technologies.react,
      Technologies.redux,
      Technologies.materialUI,
      Technologies.googleMaps,
      Tools.webpack,
      Tools.aws,
      Tools.zeplin,
      Tools.jira,
    ],
    responsibilities: [
      'SPA, Application architecture design, developing UI components (Component model  React + Redux), Unit tests',
      'Collaboration with the customer, improvements and suggestions',
      'Integration with other REST API services: (Google APIs)',
      'Lighthouse optimization',
      'Bug-fixing',
    ],
    countryCode: 'se',
    period: '11 months',
  },
  {
    name: 'Think Research Corporation',
    description: 'Healthcare Software Company developing knowledge-based tools that empower clinicians to deliver the best evidence-based care to patients, driving better patient outcomes.',
    technologies: [
      Languages.javascript,
      Technologies.react,
      Technologies.redux,
      Technologies.semanticUI,
      Technologies.styledComponents,
      Technologies.jest,
      Technologies.googleMaps,
      Tools.webpack,
      Tools.zeplin,
      Tools.jira,
    ],
    responsibilities: [
      'Development of graphical interfaces',
      'Task estimation',
      'Conduct regular code reviews to improve code quality',
      'Code refactoring and optimization',
      'Writing unit test',
      'Bug-fixing',
    ],
    countryCode: 'ca',
    period: '7 months',
  },
  {
    name: 'Disney',
    description: 'DSNY-ATHN, Disney ABC Television Group is determined to consolidate its video and game content management into the Athena Portal. The main goal of the Portal is to provide an internal powerful mechanism for content broadcasting configuration known as policies. To achieve the goal Athena Portal provides content browsing mechanism with flexible search functionality, recent activities dashboard, drag-n-drop, contextual menu, favoriting, reports generation. User roles and permission grant different access levels.',
    technologies: [
      Languages.typescript,
      Technologies.angular,
      Technologies.rxjs,
      Technologies.materialUI,
      Technologies.svg,
      Technologies.jasmine,
      Tools.webpack,
      Tools.jira,
    ],
    responsibilities: [
      'Planning',
      'Task estimation',
      'Develop UI interfaces',
      'Conduct regular code reviews to improve code quality',
      'Writing unit test',
      'Bug-fixing',
    ],
    countryCode: 'us',
    period: '3 months',
  },
  {
    name: 'Ticketmaster',
    description: 'TKM-AMS, The primary goal of the project is to develop a tool that will quickly help customer to find required information about assets of the company such as Products, Components, Virtual Machines, Physical Servers etc (up to 50+ of different types) and be able to react efficiently during the escalation and problem solving cases. The secondary goal of the project is to deliver the solution that will be able to store and keep all information about a customer\'s assets that will be a reliable and single source of data related to properties of assets, their links in between assets and ownership relations. Currently the portal handles 32k+ of different assets, 21k+ of links in between them and is ready to grow quickly in terms of numbers with remaining uptime > 99.95 and disaster recovery plan and in terms of additional features based on core flexible search functionality.',
    technologies: [
      Languages.javascript,
      Technologies.react,
      Technologies.redux,
      Technologies.materialUI,
      Technologies.d3js,
      Tools.webpack,
      Tools.zeplin,
      Tools.jira,
    ],
    responsibilities: [
      'Planning',
      'Estimations',
      'Development of UI components',
      'Conduct regular code reviews to improve code quality',
      'Integration with REST API services',
      'Integration Google Analytics',
      'Sonar Analysis',
      'Bug-fixing',
    ],
    countryCode: 'us',
    period: '8 months',
  },
  {
    name: 'Appery.io',
    description: 'Appery.io is a rapid development, integration and deployment platform for delivering cross-device apps in the enterprise. It combines enterprise-grade integration middleware with a browser-based rapid development environment and mobile backend services to accelerate enterprise mobilization. Appery.io enables developers and business analysts to rapidly create and run apps that help businesses of all sizes increase revenues and improve productivity.',
    technologies: [
      Languages.javascript,
      Technologies.postgresql,
      Technologies.angularjs,
      Technologies.backbone,
      Technologies.bootstrap,
      Technologies.jquery,
      Tools.grunt,
      Tools.jasper,
      Tools.jenkins,
      Tools.jira,
    ],
    responsibilities: [
      'Develop UI interfaces, special features and functionality, animations',
      'Conduct regular code reviews to improve code quality',
      'Writing unit test',
      'Set up Google Analytics, tracking events',
      'Optimizely (A/B testing)',
      'Bug-fixing',
      'Report System (JasperReports)',
    ],
    countryCode: 'us',
    period: '1.7 years',
  },
];
