export enum Language {
  JAVASCRIPT = 'javascript',
  TYPESCRIPT = 'typescript',
  DART = 'dart',
  JAVA = 'java',
  OBJECTIVE_C = 'objectiveC',
  PYTHON = 'python'
}

export enum Tool {
  NPM = 'npm',
  VS_CODE = 'VSCode',
  GIT = 'git',
  WEBPACK = 'webpack',
  VITE = 'vite',
  GRUNT = 'grunt',
  WEBSTORM_IDEA = 'webstorm',
  FIREBASE = 'firebase',
  SONAR = 'sonar',
  GLA = 'gla',
  ZEPLIN = 'zeplin',
  FIGMA = 'figma',
  JENKINS = 'jenkins',
  AWS = 'aws',
  JASPER = 'jasper',
  JIRA = 'jira',
  AZURE = 'azure',
  DOCKER = 'docker',
  XCODE = 'xCode',
  ANDROID_STUDIO = 'androidStudio'
}

export enum Technology {
  NODE = 'node',
  EXPRESS = 'express',
  MYSQL = 'mysql',
  POSTGRESQL = 'postgresql',
  MONGO = 'mongo',
  WEB_STORAGES = 'webStorages',
  REST = 'rest',
  GRAPHQL = 'graphql',
  WEB_SOCKET = 'webSocket',
  WEB_WORKER = 'webWorker',
  SERVICE_WORKER = 'serviceWorker',
  HTML = 'html',
  CSS = 'css',
  REACT = 'react',
  REACT_CONTEXT = 'reactContext',
  REACT_NATIVE = 'reactNative',
  CAPACITOR = 'capacitor',
  FLUTTER = 'flutter',
  ANGULAR = 'angular',
  ANGULARJS = 'angularjs',
  BACKBONE = 'backbone',
  JQUERY = 'jquery',
  REDUX = 'redux',
  MOBX = 'mobx',
  RXJS = 'rxjs',
  ZUSTAND = 'zustand',
  SVG = 'svg',
  D3JS = 'd3js',
  CANVAS = 'canvas',
  MICRO_FRONT_END = 'microFrontEnd',
  ANT_DESIGN = 'antDesign',
  MATERIAL_UI = 'materialUI',
  SEMANTIC_UI = 'semanticUI',
  KENDO_UI = 'kendoUI',
  BOOTSTRAP = 'bootstrap',
  STYLED = 'styledComponents',
  GOOGLE_MAPS = 'googleMaps',
  LODASH = 'lodash',
  CRYPTO_JS = 'cryptoJS',
  JEST = 'jest',
  CYPRESS = 'cypress',
  DETOX = 'detox',
  JASMINE = 'jasmine',
  JSDOC = 'jsdoc',
  OOP = 'oop',
  FP = 'fp',
  TDD = 'tdd',
  BDD = 'bdd',
  SCRUM = 'scrum',
  KANBAN = 'kanban',
  LEAN = 'lean',
  EXP = 'exp',
  PEXELS = 'pexels'
}

export enum Development {
  PL = 'language',
  TOOL = 'tool',
  TECHNOLOGY = 'technology',
}
